spring:
  session:
    store-type: redis
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace
        EnumType: trace
